### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by salsam** [Samppaa/Matkansuunnittelija#1]
Projekti ladattu 18.06.2016 kello 14:20.

Koodi oli kauttaaltaan clean code-vaatimusten mukainen, enkä huomannut rakenteessa mitään parannettavaa. Testit olivat kattavat ja checkstyle-reporttikin puhdas. Ainoa huomautettava asia clean codesta on TravelPlancontrolerin pituus, joka menee 20 riviä yli vaatimusten, mutta luokan koodista näyttäisi puolet olevan javadoccia ja single responsibility näyttää myös toimivan.

Rakenne tuntui todella selkeältä ja tuskailtuani itse sen kanssa oli kiva nähdä malliesimerkki selkeästä rakenteesta. HTML/CSS-osuuden luulen ymmärtäneeni, vaikken ole ikinä ohjelmoinut CSS/HTML-koodia, joten eiköhän sekin ollut hyvin tehty. Tuo statuskoodi-idea näytti itseässä todella hyvältä ja aion itse panna sen muistiin, sillä se teki koodista paljon selkeämmän.

GUI oli selkeä ja helpot virhetapaukset, kuten väärät syötteet oli käsitelty. GUIn luomassa HTML-tiedostossa ääkköset eivät tosin näkyneet oikein, joten sen voisi ehkä korjata määräämällä eri kielipaketin käyttöön.

Ainoa muu "virhe", jonka huomasin oli, ettei javadocissa ollut pilkkuja ennen esim. sanaa joka. Tämä tosin on jo aika pientä, joten ei muuta kuin peukkuja minulta :).

**Comment by Samppaa** [comment]
Kiitos kommenteista.
